name: Integration Checks

on:
  push:
    branches: ["main"]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.22.2
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet .

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
